# 1. Getting started with NumPy


In [2]:
import numpy as np

In [3]:
# Sides of Square
square_sides = [4, 5, 6, 7, 9, 89, 99]

In [5]:
sides_array = np.array(square_sides)

area_array = sides_array * sides_array
print(area_array)

[  16   25   36   49   81 7921 9801]


## Array example

In [6]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,4,3,2,1])

array1 +  array2

array([6, 6, 6, 6, 6])

## Calculate BMI

In [9]:
height = np.array([1.72, 1.75, 1.72, 1.45, 1.50, 2.10])
weight = np.array([65, 75, 99, 33, 45, 95])

# Calculate BMI weigt/height**2
bmi_array = weight/(height**2)
bmi_array

array([21.97133586, 24.48979592, 33.46403461, 15.69560048, 20.        ,
       21.54195011])

In [10]:
bmi_array[0]

21.971335857220122

In [11]:
bmi_array[-1]

21.541950113378682

## Convert to 2D array

In [14]:
bmi_array.reshape(3, 2)

array([[21.97133586, 24.48979592],
       [33.46403461, 15.69560048],
       [20.        , 21.54195011]])

## Atributers of numpy array

In [18]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(np_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# Check size
np_array.size

12

In [20]:
# Check shape
np_array.shape

(4, 3)

In [21]:
# Check dimensions
np_array.ndim

2

In [22]:
# Check datatype
np_array.dtype

dtype('int32')

## Methods to create NumPy arrays

1. array()
2. ones()
3. zeros()
4. arange()
5. linspace()
6. random.random()

In [26]:
# array() from list
player_height = [1.5, 1.7, 1.55, 1.68, 1.99, 1.87, 2.1, 1.45, 1.99, 1.83]

np_height = np.array(player_height)
np_height

array([1.5 , 1.7 , 1.55, 1.68, 1.99, 1.87, 2.1 , 1.45, 1.99, 1.83])

In [28]:
# array() from dictionary
currency = {"Dollar": "$", "Pound": "£", "Euro": "€"}
np_currency = np.array(list(currency.items()))
np_currency

array([['Dollar', '$'],
       ['Pound', '£'],
       ['Euro', '€']], dtype='<U6')

In [30]:
# ones()
array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
arr_ones = np.ones(10, dtype=int)
arr_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
arr_ones.reshape(2, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
arr_ones.itemsize

4

In [37]:
# zeros()
array_zeros = np.zeros(20)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [40]:
arr_zeros = np.zeros(dtype=int, shape=(4, 3))
arr_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
# arange()
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
# linspace()
np.linspace(1, 500, 30)

array([  1.        ,  18.20689655,  35.4137931 ,  52.62068966,
        69.82758621,  87.03448276, 104.24137931, 121.44827586,
       138.65517241, 155.86206897, 173.06896552, 190.27586207,
       207.48275862, 224.68965517, 241.89655172, 259.10344828,
       276.31034483, 293.51724138, 310.72413793, 327.93103448,
       345.13793103, 362.34482759, 379.55172414, 396.75862069,
       413.96551724, 431.17241379, 448.37931034, 465.5862069 ,
       482.79310345, 500.        ])

In [45]:
# random.random()
np.random.random()

0.42777382055611735

In [46]:
np.random.random([5,4])

array([[0.05603996, 0.84340763, 0.99380579, 0.04986457],
       [0.90679013, 0.06350956, 0.24368683, 0.21968469],
       [0.75605645, 0.13047183, 0.26994372, 0.71209758],
       [0.11482638, 0.07680708, 0.31567559, 0.37891666],
       [0.19764951, 0.82615023, 0.7938021 , 0.24198946]])

In [48]:
np.random.random([5, 4]) * 100

array([[45.84189151, 76.35750406, 43.28734793, 26.24984098],
       [ 1.19726903, 25.10238425, 17.14997679, 14.22543174],
       [39.94387771, 16.38999013, 93.41300418, 93.59369495],
       [66.57664502, 29.58785615, 47.5738848 , 12.83642504],
       [49.54555211, 49.07916026, 25.14270253,  5.9958787 ]])

In [50]:
np.random.random([4, 5]) * 12

array([[ 6.89125853, 10.13925992,  8.66105864,  1.70582958,  4.04365843],
       [ 9.1325605 ,  3.55977632,  6.20203386, 10.94605115,  7.49092865],
       [10.25029525,  5.13465888,  8.71925978,  4.17870565,  7.63508709],
       [ 9.59110136,  4.64700352,  0.26360283, 10.0604883 ,  1.36747062]])

In [52]:
np_int32 = (np.random.random([4, 5]) * 12).astype("int32")
np_int32

array([[11,  3,  4,  2,  0],
       [ 0,  3, 11,  4,  2],
       [ 5,  2,  8,  7,  5],
       [ 1,  9,  2,  8,  5]])

## Indexing

In [53]:
# row
np_int32[1]

array([ 0,  3, 11,  4,  2])

In [54]:
# column
np_int32[:,-2]

array([2, 4, 7, 8])

In [61]:
# row and column
np_int32[0:3, -1]
np_int32[:, 1]

array([3, 3, 2, 9])

## Sub-array

In [74]:
A = np_int32[1:3, 1:4]
A

array([[ 3, 11,  4],
       [ 2,  8,  7]])

In [77]:
B = A[[0, 1, 1], [1, 2, 1]] # [rows], [columns]
B

array([11,  7,  8])